name: game_core
description: Core game domain interfaces and GameCore implementation for main app state.
version: 0.1.0
environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  meta: ^1.9.0

dev_dependencies:
  test: ^1.21.0
