name: sozzle
description: Sozzle a word puzzle game made with Fluttter
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=3.1.0 <4.0.0"

dependencies:
  animated_text_kit: ^4.2.2
  audioplayers: ^6.0.0
  bloc: ^8.1.4
  circular_pattern: ^0.0.3
  device_preview: ^1.2.0
  equatable: ^2.0.5
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.5
  flutter_localizations:
    sdk: flutter
  go_router: ^14.1.4
  grid_board:
    git:
      url: https://github.com/agtrlabs/grid_board.git
      ref: 7690c9b
  http: ^1.2.1
  intl: ^0.19.0
  level_data:
    path: packages/level_data
  localstore: ^1.4.0
  rive: ^0.13.5
  # TODO(RIVE): Reinstall flutter on linux and uncomment level_complete_page.dart
#  rive: ^0.12.3

dev_dependencies:
  bloc_test: ^9.1.7
  flutter_test:
    sdk: flutter
  mocktail: ^1.0.3
  very_good_analysis: ^5.1.0

flutter:
  uses-material-design: true
  generate: true
  assets:
    - assets/sfx/
    - assets/rive/
