name: sozzle
description: Sozzle a word puzzle game made with Fluttter
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=3.1.0 <4.0.0"

dependencies:
  animated_text_kit: ^4.2.2
  audioplayers: ^1.1.1
  bloc: ^8.1.0
  circular_pattern: ^0.0.2
  device_preview: ^1.1.0
  equatable: ^2.0.5
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.1
  flutter_localizations:
    sdk: flutter
  go_router: ^12.1.1
  grid_board:
    git:
      url: https://github.com/agtrlabs/grid_board.git
      ref: 7690c9b
  http: ^0.13.5
  intl: ^0.18.1
  level_data:
    path: packages/level_data
  localstore: ^1.2.3
  # TODO(RIVE): Reinstall flutter on linux and uncomment level_complete_page.dart
#  rive: ^0.12.3

dev_dependencies:
  bloc_test: ^9.1.0
  flutter_test:
    sdk: flutter
  mocktail: ^0.3.0
  very_good_analysis: ^3.0.2

flutter:
  uses-material-design: true
  generate: true
  assets:
    - assets/sfx/
    - assets/rive/
