name: level_generator
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.1.0-287.0.dev <4.0.0'




dependencies:
  cupertino_icons: ^1.0.8
  dartz: ^0.10.1
  equatable: ^2.0.5
  flutter:
    sdk: flutter
  level_data:
    path: ../packages/level_data


dev_dependencies:
  flutter_lints: ^4.0.0
  flutter_test:
    sdk: flutter
  mocktail: ^1.0.3

flutter:
  uses-material-design: true

  assets:
    - assets/



























