name: level_generator
description: The engine that handles level generation logic
version: 0.1.0+1
publish_to: none

environment:
  sdk: ^3.9.0

dependencies:
  equatable: ^2.0.7
  free_dictionary_api_v2: ^1.0.3
  http: ^1.5.0
  level_data:
    path: ../level_data


dev_dependencies:
  mocktail: ^1.0.4
  test: ^1.26.3
  very_good_analysis: ^10.0.0
