name: level_data
description: Level domain for Sozzle
version: 1.0.0
publish_to: 'none'

environment:
  sdk: ^3.9.0

dependencies: {equatable: ^2.0.7}

dev_dependencies:
  lints: ^2.0.0
  test: ^1.16.0
  very_good_analysis: ^10.0.0
