name: sozzle

on: [pull_request]

jobs:
  semantic-pull-request:
    uses: VeryGoodOpenSource/very_good_workflows/.github/workflows/semantic_pull_request.yml@v1

  build:
    uses: VeryGoodOpenSource/very_good_workflows/.github/workflows/flutter_package.yml@v1
    with:
      flutter_channel: stable
      flutter_version: 3.35.6
      min_coverage: 70
      setup_command: sudo apt-get update && sudo apt-get install -y libgl1-mesa-glx libegl1-mesa-dev
